# Default values for dm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

globals:
  versions-repo-url: git://foo
  image:
    repository: dm
    tag: latest
    pullPolicy: IfNotPresent
